import type { Metadata } from "next";
import Header from "@/app/components/layout/header";
import Footer from "@/app/components/layout/footer";
import Main from "@/app/components/layout/main";
import LogoutButton from "@/app/components/parts/button/logout-button";

export const metadata: Metadata = {
  title: "lv99",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header>
        <LogoutButton />
      </Header>
      <Main>
        {children}
      </Main>
      <Footer />
    </>
  );
}
