export const dynamic = 'force-dynamic';

import React from 'react';
import { Metadata } from 'next';
import styles from './page.module.css';
import { api } from '@/lib/api/api.server';
import { Account } from '@/types/models';

export const metadata: Metadata = {
  title: "lv99 - dashboard",
  description: "Generated by create next app",
};

const AdminPage: React.FC = async () => {
  const data: Account = await api.get('accounts/me');
  const counts: any[] = await api.get('comments/count');
  console.log('counts', counts);
  return (
    <div className={styles.container}>
      ようこそ {data.name} さん
    </div>
  );
};

export default AdminPage;
