CREATE TABLE IF NOT EXISTS account (
	account_id SERIAL PRIMARY KEY,
	account_name TEXT NOT NULL UNIQUE,
	account_password TEXT NOT NULL,
  account_role INTEGER NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);