CREATE TABLE IF NOT EXISTS comment (
  comment_id SERIAL PRIMARY KEY,
  answer_id INTEGER NOT NULL REFERENCES answer(answer_id) ON DELETE CASCADE,
  account_id INTEGER NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  comment_content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);