export const dynamic = 'force-dynamic';

import React from 'react';
import { Metadata } from 'next';
import styles from './page.module.css';
import { api } from '@/lib/api/api.server';
import { AccountWithProfile } from '@/types/models';
import AccountList from './account-list';

export const metadata: Metadata = {
  title: "lv99 - dashboard",
  description: "Generated by create next app",
};

const AccountsPage: React.FC = async () => {
  const data: AccountWithProfile[] = await api.get('admin/accounts/with-profile');
  console.log(data);
  return (
    <div className={styles.container}>
      <AccountList accounts={data} />
    </div>
  );
};

export default AccountsPage;
