export const dynamic = 'force-dynamic';

import React from 'react';
import { Metadata } from 'next';
import styles from './page.module.css';
import { api } from '@/lib/api/api.server';
import { Account } from '@/types/models';
import PasswordForm from './password-form';

export const metadata: Metadata = {
  title: "lv99 - home",
  description: "Generated by create next app",
};

const AccountPage: React.FC = async () => {
  const account: Account = await api.get('accounts/me');
  const profile: any = await api.get('accounts/me/profile');

  console.log('account', account);
  console.log('profile', profile);

  return (
    <div className={styles.container}>
      <label>ログインユーザ名</label>
      <input type="text" disabled value={account.name} className={styles.input} />

      <div>パスワード変更</div>
      <PasswordForm />

      <div>プロフィール</div>
      <label>表示名</label>
      <input type="text" value={profile.display_name} className={styles.input} />
    </div>
  );
};

export default AccountPage;
