export const dynamic = 'force-dynamic';

import React from 'react';
import { Metadata } from 'next';
import styles from './page.module.css';
import { api } from '@/lib/api/api.server';
import { Answer } from '@/types/models';
import AnswerList from './answer-list';

export const metadata: Metadata = {
  title: "lv99 - dashboard",
  description: "Generated by create next app",
};

const AnswersPage: React.FC = async () => {
  const data: any[] = await api.get('admin/answers/search');
  console.log(data);
  return (
    <div className={styles.container}>
      <AnswerList answers={data} />
    </div>
  );
};

export default AnswersPage;
